import logo1 from "./../../../assets/logo1.png";
import logo2 from "./../../../assets/logo2.png";
import logo3 from "./../../../assets/logo3.png";
import logo4 from "./../../../assets/logo4.png";
import logo5 from "./../../../assets/logo5.png";

const mockData = [
    {
      casinoName: "Ripper Casino",
      exclusive: false,
      bonusValue: 1001,
      countFreeSpins: 90,
      typeOfBonus: "no deposit",
      logoSrc: logo1,
      key: 1,
    },
    {
      casinoName: "Ripper Casino",
      exclusive: true,
      bonusValue: 1992,
      countFreeSpins: 90,
      typeOfBonus: "no deposit",
      logoSrc: logo2,
      key: 2,
    },
    {
      casinoName: "Ozwin Casino",
      exclusive: false,
      bonusValue: 2003,
      countFreeSpins: 90,
      typeOfBonus: "welcome",
      logoSrc: logo3,
      key: 3,
    },
    {
      casinoName: "Fair Go Casino",
      exclusive: true,
      bonusValue: 5006,
      countFreeSpins: 90,
      typeOfBonus: "welcome",
      logoSrc: logo4,
      key: 4,
    },
    {
      casinoName: "Fair Go Casino",
      exclusive: false,
      bonusValue: 7002,
      countFreeSpins: 90,
      typeOfBonus: "free spins",
      logoSrc: logo5,
      key: 5,
    },
    {
      casinoName: "Hell Spin Casino",
      exclusive: true,
      bonusValue: 500,
      countFreeSpins: 90,
      typeOfBonus: "free spins",
      logoSrc: logo1,
      key: 6,
    },
    {
      casinoName: "Bizzo Casino",
      exclusive: false,
      bonusValue: 100,
      countFreeSpins: 90,
      typeOfBonus: "no deposit",
      logoSrc: logo2,
      key: 7,
    },
    {
      casinoName: "Arc Casino",
      exclusive: true,
      bonusValue: 4006,
      countFreeSpins: 90,
      typeOfBonus: "no deposit",
      logoSrc: logo3,
      key: 8,
    },
    {
      casinoName: "War Casino",
      exclusive: false,
      bonusValue: 1002,
      countFreeSpins: 90,
      typeOfBonus: "welcome",
      logoSrc: logo4,
      key: 9,
    },
    {
      casinoName: "Bizzo Casino",
      exclusive: true,
      bonusValue: 100,
      countFreeSpins: 90,
      typeOfBonus: "no deposit",
      logoSrc: logo5,
      key: 10,
    },
    {
      casinoName: "Arc Casino",
      exclusive: true,
      bonusValue: 4001,
      countFreeSpins: 90,
      typeOfBonus: "no deposit",
      logoSrc: logo1,
      key: 11,
    },
    {
      casinoName: "War Casino",
      exclusive: false,
      bonusValue: 100,
      countFreeSpins: 90,
      typeOfBonus: "no deposit",
      logoSrc: logo2,
      key: 12,
    },
    {
      casinoName: "Bizzo Casino",
      exclusive: false,
      bonusValue: 100,
      countFreeSpins: 90,
      typeOfBonus: "welcome",
      logoSrc: logo3,
      key: 13,
    },
    {
      casinoName: "Arc Casino",
      exclusive: true,
      bonusValue: 400,
      countFreeSpins: 90,
      typeOfBonus: "free spins",
      logoSrc: logo4,
      key: 14,
    },
    {
      casinoName: "War Casino",
      exclusive: false,
      bonusValue: 100,
      countFreeSpins: 90,
      typeOfBonus: "no deposit",
      logoSrc: logo5,
      key: 16,
    },
    {
      casinoName: "War Casino",
      exclusive: false,
      bonusValue: 100,
      countFreeSpins: 90,
      typeOfBonus: "welcome",
      logoSrc: logo5,
      key: 17,
    },
    {
      casinoName: "War Casino",
      exclusive: false,
      bonusValue: 100,
      countFreeSpins: 90,
      typeOfBonus: "welcome",
      logoSrc: logo5,
      key: 18,
    },
    {
      casinoName: "War Casino",
      exclusive: false,
      bonusValue: 100,
      countFreeSpins: 90,
      typeOfBonus: "welcome",
      logoSrc: logo5,
      key: 19,
    },
    {
      casinoName: "War Casino",
      exclusive: false,
      bonusValue: 100,
      countFreeSpins: 90,
      typeOfBonus: "no deposit",
      logoSrc: logo5,
      key: 20,
    },
    {
      casinoName: "War Casino",
      exclusive: false,
      bonusValue: 100,
      countFreeSpins: 90,
      typeOfBonus: "no deposit",
      logoSrc: logo5,
      key: 21,
    },
  ];

  export default mockData;